version: '3'

services:
  db:
    image: postgres:latest
    container_name: currency-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env 

volumes:
  postgres_data: